Upgrade to mui v5 Getting runtime errors in the browser about the style and theme not being set up right. getStylesCreator.js:24 MUI: The styles argument provided is invalid. You are providing a function without a theme in the context. One of the parent elements needs to use a ThemeProvider. create @ getStylesCreator.js:24 getStylesCreator.js:28 Uncaught TypeError: theme.spacing is not a function